apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/argocd
    repoURL:  git@github.com:stieglma/ieee-docker-kube-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
      - /spec/syncPolicy/automated
      managedFieldsManagers:
      - argocd-server
