apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ieee-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: ieee-gitops-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/ieee-demo
    repoURL:  git@github.com:stieglma/ieee-docker-kube-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
