apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/install.yaml
  - argo-ingress.yaml
  - argocd-secret.yaml
  - argocd-default-project.yaml
  - ./apps
patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-default-secret-delete.yaml
  - argocd-pull-policy.yaml
